### ISSUE TITLE
Detecting Xbox Series X|S on UWP fails

### ISSUE THREAD

**Issue by RustyMoyher** [walbourn/walbourn.github.io#19]
Using `GetGamingDeviceModelInformation()` to get the `info.deviceId`, as recommended on the [DirectX and UWP on Xbox One post](https://walbourn.github.io/directx-and-uwp-on-xbox-one/), returns on unexpected result on Xbox Series X|S. The newer consoles return `GAMING_DEVICE_DEVICE_ID_XBOX_ONE`, which is the original Xbox One console. The [post](https://walbourn.github.io/directx-and-uwp-on-xbox-one/) suggests that newer devices would return something different and “default” could be used for Forward compatibility. (Note: I've only tested this on Series X. I'm unsure what Series S returns.)

Is this a bug? I’d like to create a 4K swap chain on Series X|S. Is there an alternative way to detect these newer devices?

I apologize if this is the wrong channel to ask this question. Thanks for your helpful DirectX blog!

**Comment by walbourn** [comment]
Thanks. I've noted this issue internally, but I'm not sure there's been any real progress on getting it fixed. For Xbox Series X, 4k works fine. For Xbox Series S, 4k will also work but 1440p is actually better suited for real-time rendering.

> Xbox One (Durango) was particularly problematic because you can create a 4k render target, but the hardware can't actually scale it down so it fails to render anything at all.

**Comment by RustyMoyher** [comment]
Thanks Chuck! That’s super helpful.

My current workaround is unfortunately to just use 1080p for everything. Because I can’t detect the Xbox Series X or S, I don’t know when it’s OK to create a 4K swap chain. Would just crash on Xbox One (Durango).

Good notes on Xbox Series S performance profile! I feel confident we could hit a solid 4K @ 60FPS on our current project, but will confirm on hardware first of course. :)

**Comment by walbourn** [comment]
Good news. This is fixed for the April 2022 recovery. I'll be posting a follow-in up to https://walbourn.github.io/directx-and-uwp-on-xbox-one/ shortly with the dets.
