### ISSUE TITLE
"Legacy D3DX on NuGet" refers to an inexistant DLL

### ISSUE THREAD

**Issue by CookiePLMonster** [walbourn/walbourn.github.io#24]
[THIS BLOG POST](https://walbourn.github.io/legacy-d3dx-on-nuget/) says
> When it comes time to ship your game or application, just ship the D3DX9_43.DLL, D3DX10_43.DLL, and/or D3DX11_43.DLL along with D3DCompile_43.DLL

I assume it meant to say `D3DCompiler_47.DLL` (or `D3DCompiler_43.DLL`) instead.

**Comment by walbourn** [comment]
Thanks! Fixing it now.
