### ISSUE TITLE
GDC 2019

### ISSUE THREAD

**Issue by walbourn** [walbourn/walbourn.github.io#3]
Links when presentations are out...

**Comment by ghost** [comment]
Do we have links to the talks that go with these presentations?

**Comment by walbourn** [comment]
The videos are all on [YouTube](https://www.youtube.com/playlist?list=PLRs2lXTYCDQ3q9WF-4aO2SgCCCL6rSmA6)

**Comment by walbourn** [comment]
See [this commit](https://github.com/walbourn/walbourn.github.io/commit/879cb32edf1e4fe34aec10afa2729a40ff66d593)
